version: "3"
services:
  web:
    image: public.ecr.aws/c5t5r6r7/airbnb-flask:web
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=0
    networks:
      - airbnb_network

  proxy:
    image: public.ecr.aws/c5t5r6r7/airbnb-flask:proxy
    restart: always
    ports:
      - 80:80
    networks:
      - airbnb_network

  db:
    image: public.ecr.aws/c5t5r6r7/airbnb-flask:db
    restart: always
    ports:
      - 5432:5432
    networks:
      - airbnb_network
    volumes:
      - postgres_db:/var/lib/postgresql/data

networks:
  airbnb_network:

volumes:
  postgres_db: