version: "3.7"
services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=0
    networks:
      - airbnb_network

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - airbnb_network
  db:
    build: db
    restart: always
    ports:
      - 5432:5432
    networks:
      - airbnb_network
    volumes:
      - postgres_db:/var/lib/postgresql/data

networks:
  airbnb_network:

volumes:
  postgres_db: